---
- name: Satellite server pre-install preparation.
  hosts: satellite-server
  environment:
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8
  vars_files:
    - group_vars/all
    - group_vars/private

  tasks:

  - name: Set hostname.
    hostname:
      name: satellite.lab
    tags:
      - pre_task
  
  - name: Open firewall ports.
    ansible.posix.firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
    loop: "{{ satellite_ports }}"
    tags:
      - pre_task

  - name: Remove rhui repos.
    yum:
      name: google-rhui-client*
      state: removed
    tags:
      - pre_task

  - name: Register host with subscription manager.
    redhat_subscription:
      state: present
      activationkey: "{{ satellite_activation_key }}"
      org_id: "{{ org_id }}"
      auto_attach: true
    tags:
      - pre_task

  - name: Configure the installer repos.
    rhsm_repository:
      name: "{{ satellite_repositories }}"
      state: enabled
      purge: yes
    tags:
      - pre_task
  
  - name: Update all packages.
    yum:
      name: "*"
      state: latest
    tags:
      - pre_task
  
  - name: Install the Satellite RPM.
    yum:
      name: satellite
      state: latest
      skip_broken: yes
    tags:
      - pre_task

  # - name: Install chrony.
  #   include_role:
  #     name: oasis_roles.system.chrony
  #   tags:
  #     - software
    
  - name: Check if Satellite is installed and running.
    shell: >-
      satellite-maintain service status --brief | grep 'All services are running'
    ignore_errors: true
    register: satellite_status

  - name: Run the Satellite installer.
    include_role:
      name: redhat.satellite_operations.installer
    vars:
      satellite_installer_scenario: satellite
      satellite_installer_options:
          - "--foreman-initial-admin-username {{ admin_user }}"
          - "--foreman-initial-admin-password {{ admin_password }}"
      satellite_installer_command: satellite-installer
    when:
      - satellite_status.stdout is defined
      - not 'OK' in satellite_status.stdout
    tags:
      - software
